### PR TITLE
Mostly copy in .gitattributes from master

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Master has it wrong. tests/ cannot be excluded since it is (unfortunately) not fully package private. https://github.com/DataValues/Common/blob/master/composer.json#L47

**Comment by JeroenDeDauw** [comment]
Master fix: https://github.com/DataValues/Common/pull/85

**Comment by reedy** [comment]
> Master has it wrong. tests/ cannot be excluded since it is (unfortunately) not fully package private. https://github.com/DataValues/Common/blob/master/composer.json#L47

What do you mean?

Tests shouldn't be needed when installing via composer...

**Comment by JeroenDeDauw** [comment]
There is a test base class used by other packages. Bad design from 2012 says hello. https://github.com/DataValues/Common/blob/master/tests/ValueParsers/ValueParserTestBase.php

**Comment by JeroenDeDauw** [comment]
Been removing code using shit like this for years. This base class still has [some users](https://github.com/DataValues/Common/issues/86). Help with killing those is welcome

**Pull request merged**
